name: Build

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-windows:
    name: WinUser
    needs: []
    strategy:
      fail-fast: false
      matrix:
        config: ['Debug', 'Release']
        plat: [windows, uwp] # TODO: Support gamecore_console
        os: ['windows-2022']
        arch: [x86, x64, arm64]
        tls: [schannel, openssl, openssl3]
        static: ['', '-Static']
        exclude:
        # OpenSSL doesn't support arm64
        - tls: openssl
          arch: arm64
        # OpenSSL3 doesn't support arm64
        - tls: openssl3
          arch: arm64
        # TODO: FIX: OpenSSL3 build fails with UWP
        - plat: uwp
          tls: openssl3
        # TODO: FIX: Static builds fail with UWP
        - plat: uwp
          static: '-Static'
    uses: ./.github/workflows/build-reuse-win.yml
    with:
      config: ${{ matrix.config }}
      plat: ${{ matrix.plat }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      tls: ${{ matrix.tls }}
      static: ${{ matrix.static }}

