name: Build

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-windows:
    name: WinUser
    needs: []
    strategy:
      fail-fast: false
      matrix:
        config: ['Debug']
        plat: [windows] # TODO: Support gamecore_console
        os: ['windows-2022']
        arch: [x64]
        tls: [schannel]
        static: ['', '-Static']
        exclude:
        # OpenSSL doesn't support arm64
        - tls: openssl
          arch: arm64
        # OpenSSL3 doesn't support arm64
        - tls: openssl3
          arch: arm64
        # TODO: FIX: OpenSSL3 build fails with UWP
        - plat: uwp
          tls: openssl3
        # TODO: FIX: Static builds fail with UWP
        - plat: uwp
          static: '-Static'
    uses: ./.github/workflows/build-reuse-win.yml
    with:
      config: ${{ matrix.config }}
      plat: ${{ matrix.plat }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      tls: ${{ matrix.tls }}
      static: ${{ matrix.static }}

  # build-ubuntu:
  #   name: Ubuntu
  #   needs: []
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       config: ['Debug']
  #       plat: [linux]
  #       os: ['ubuntu-22.04']
  #       arch: [x64]
  #       tls: [openssl3]
  #       systemcrypto: ['-UseSystemOpenSSLCrypto']
  #       static: ['', '-Static']
  #       clang: ['']
  #       codecheck: ['']
  #       xdp: ['']
  #       exclude:
  #       # Android doesn't support x86
  #       - plat: android
  #         arch: x86
  #       # Android doesn't use system crypto
  #       - plat: android
  #         systemcrypto: '-UseSystemOpenSSLCrypto'
  #       # TODO: android to support ubuntu-24.04
  #       - plat: android
  #         os: 'ubuntu-24.04'
  #       # No openssl3 system crypto on ubuntu-20.04
  #       - plat: linux
  #         os: 'ubuntu-20.04'
  #         tls: 'openssl3'
  #         systemcrypto: '-UseSystemOpenSSLCrypto'
  #       # No openssl system crypto on ubuntu-22.04
  #       - plat: linux
  #         os: 'ubuntu-22.04'
  #         tls: 'openssl'
  #         systemcrypto: '-UseSystemOpenSSLCrypto'
  #       # No openssl system crypto on ubuntu-24.04
  #       - plat: linux
  #         os: 'ubuntu-24.04'
  #         tls: 'openssl'
  #         systemcrypto: '-UseSystemOpenSSLCrypto'
  #       # linux xdp is for ubuntu24.04 only for now
  #       - plat: android
  #         xdp: "-UseXdp"
  #       - os: 'ubuntu-20.04'
  #         xdp: "-UseXdp"
  #       - os: 'ubuntu-22.04'
  #         xdp: "-UseXdp"
  #       - arch: x86
  #         xdp: "-UseXdp"
  #       # Android doesn't use Clang
  #       - plat: android
  #         clang: '-Clang'
  #       # Android doesn't use CodeCheck
  #       - plat: android
  #         codecheck: '-CodeCheck'
  #       # No need to combine SystemCrypto and CodeCheck
  #       - systemcrypto: '-UseSystemOpenSSLCrypto'
  #         codecheck: '-CodeCheck'
  #       # No need to combine Static and CodeCheck
  #       - static: '-Static'
  #         codecheck: '-CodeCheck'
  #       # No need to combine Clang and CodeCheck
  #       - clang: '-Clang'
  #         codecheck: '-CodeCheck'
  #       # Release builds fail with CodeCheck
  #       - config: 'Release'
  #         codecheck: '-CodeCheck'
  #       # Static build can't dynamically link to libcrypto
  #       - systemcrypto: '-UseSystemOpenSSLCrypto'
  #         static: '-Static'
  #   uses: ./.github/workflows/build-reuse-unix.yml
  #   with:
  #     config: ${{ matrix.config }}
  #     plat: ${{ matrix.plat }}
  #     os: ${{ matrix.os }}
  #     arch: ${{ matrix.arch }}
  #     tls: ${{ matrix.tls }}
  #     systemcrypto: ${{ matrix.systemcrypto }}
  #     static: ${{ matrix.static }}
  #     clang: ${{ matrix.clang }}
  #     codecheck: ${{ matrix.codecheck }}
  #     xdp: ${{ matrix.xdp }}